name: Client Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            script: ./test_environment.sh
          - os: macos-latest
            script: ./test_environment.sh
          - os: windows-latest
            script: .\test_environment.bat --unattended
    steps:
    - uses: actions/checkout@v4
    - name: Run unittests
      run: |
        ${{ matrix.script }} -v --update-all --exec python tasks.py unittest
    - name: Check update mechanism
      run: |
        ${{ matrix.script }} -v --check-installation --fix
        ${{ matrix.script }} -v --version
